* AGILE Workflows
** Installation Instructions on a Docker Cluster

*** Alternative to Docker Desktop

    #+BEGIN_SRC: bash
    brew install hyperkit
    brew install minikube
    brew install docker
    brew install docker-compose
    minikube start --driver=hyperkit --container-runtime=docker --mount --mount-string --mount-string $(pwd):/agile-workflows -n 2
    eval $(minikube docker-env)
    echo "`minikube ip` docker.local" | sudo tee -a /etc/hosts > /dev/null
    #+END_SRC

*** Create the docker development cluster

    #+BEGIN_SRC: bash
    docker compose -f docker/docker-compose.yml build
    docker compose -f docker/docker-compose.yml up -d --scale node=2
    bash docker/gen_machines_list.sh
    #+END_SRC

*** Build the software from the head node

    #+BEGIN_SRC: bash
    ssh -p 2022 -i docker/ssh/id_rsa.mpi agile@localhost
    cd agile-workflows
    source scripts/docker_modules.sh
    source scripts/docker_setup.sh
    conan install --install-folder build . --build missing
    conan build --build-folder build .
    #+END_SRC

** Installation Instructions on the Puma Cluster

*** Load the modules and prepare for the build
   #+BEGIN_SRC: bash
   source scripts/puma_modules.sh
   #+END_SRC
*** First time setup and dependency installation
   #+BEGIN_SRC: bash
   source scripts/puma_setup.sh
   #+END_SRC
*** Build the agile-workflow package
    The conan install command is only needed the first time or after updating dependencies.

    #+BEGIN_SRC: bash
    conan install --install-folder build . --build missing
    conan build --build-folder build .
    #+END_SRC

** Run the AGILE workflows

Download the AGILE WMD Dataset:
#+BEGIN_SRC: bash
git clone git@socks.lbl.gov:iarpa-agile-gfi/pnnl/wmd-dataset.git
#+END_SRC


*** Workflow 1

#+BEGIN_SRC: bash
cd agile-workflows
./build/bin/do-workflow1 ../wmd-dataset/data.001.csv pytorch-models/workflow1-GNN.pt
#+END_SRC

To scale the workflow on a machine with MPI, you can execute the program by running:
#+BEGIN_SRC: bash
cd agile-workflows
mpiexec -n 4 --npernode 2 --bind-to socket ./build/bin/do-workflow1 ../wmd-dataset/data.001.csv pytorch-models/workflow1-GNN.pt
#+END_SRC

*** Workflow 2

**** Exact Matching

#+BEGIN_SRC: bash
cd agile-workflows
./build/bin/do-wk2_exact ../wmd-dataset/data.001.csv
#+END_SRC

To scale the workflow on a machine with MPI, you can execute the program by running:
#+BEGIN_SRC: bash
cd agile-workflows
mpiexec -n 4 --npernode 2 --bind-to socket ./build/bin/do-wk2_exact ../wmd-dataset/data.001.csv 
#+END_SRC

**** Approximate Matching

#+BEGIN_SRC: bash
cd agile-workflows
./build/bin/do-wk2_approx ../wmd-dataset/pattern1.csv ../wmd-dataset/data.001.csv <number of matches>
#+END_SRC

To scale the workflow on a machine with MPI, you can execute the program by running:
#+BEGIN_SRC: bash
cd agile-workflows
mpiexec -n 4 --npernode 2 --bind-to socket ./build/bin/do-wk2_approx ../wmd-dataset/pattern1.csv ../wmd-dataset/data.001.csv <number of matches>
#+END_SRC


**** Partial Matching
#+BEGIN_SRC: bash
cd agile-workflows
./build/bin/do-wk2_partial ../wmd-dataset/data.001.csv
#+END_SRC

To scale the workflow on a machine with MPI, you can execute the program by running:
#+BEGIN_SRC: bash
cd agile-workflows
mpiexec -n 4 --npernode 2 --bind-to socket ./build/bin/do-wk2_partial ../wmd-dataset/data.001.csv
#+END_SRC

** Pre-Copyright Notice

This computer software was prepared by Battelle Memorial Institute, hereinafter
the Contractor, under Contract No. DE-AC05-76RL01830 with the Department of
Energy (DOE). All rights in the computer software are reserved by DOE on behalf
of the United States Government and the Contractor as provided in the Contract.
You are authorized to use this computer software for Governmental purposes but
it is not to be released or distributed to the public. NEITHER THE GOVERNMENT
NOR THE CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY
LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this sentence must
appear on any copies of this computer software.

** Disclaimer Notice

This material was prepared as an account of work sponsored by an agency of the
United States Government. Neither the United States Government nor the United
States Department of Energy, nor Battelle, nor any of their employees, nor any
jurisdiction or organization that has cooperated in the development of these
materials, makes any warranty, express or implied, or assumes any legal
liability or responsibility for the accuracy, completeness, or usefulness or any
information, apparatus, product, software, or process disclosed, or represents
that its use would not infringe privately owned rights. Reference herein to any
specific commercial product, process, or service by trade name, trademark,
manufacturer, or otherwise does not necessarily constitute or imply its
endorsement, recommendation, or favoring by the United States Government or any
agency thereof, or Battelle Memorial Institute. The views and opinions of
authors expressed herein do not necessarily state or reflect those of the United
States Government or any agency thereof.

#+BEGIN_CENTER
                     PACIFIC NORTHWEST NATIONAL LABORATORY
                                  operated by
                                    BATTELLE
                                    for the
                       UNITED STATES DEPARTMENT OF ENERGY
                        under Contract DE-AC05-76RL01830
#+END_CENTER
