#ifndef GRAPHTYPES_H_
#define GRAPHTYPES_H_

namespace agile::workflow2 {

enum class TYPES {
  PERSON,
  FORUMEVENT,
  FORUM,
  PUBLICATION,
  TOPIC,
  PURCHASE,
  SALE,
  AUTHOR,
  INCLUDES,
  HASTOPIC,
  HASORG,
  NONE
};

enum class TRIPLES {
  PERSON_SALE_PERSON,
  PERSON_PURCHASE_PERSON,
  PERSON_AUTHOR_FORUMEVENT,
  PERSON_AUTHOR_PUBLICATION,
  FORUMEVENT_HASTOPIC_TOPIC,
  FORUM_HASTOPIC_TOPIC,
  FORUM_INCLUDES_FORUMEVENT,
  PUBLICATION_HASORG_TOPIC,
  PUBLICATION_HASTOPIC_TOPIC,
  NONE
};

using Triples = uint64_t [(uint64_t) TRIPLES::NONE];
constexpr uint64_t NUMTRIPLES = (uint64_t) TRIPLES::NONE;

} // namespace agile::workflow2

#endif // GRAPHTYPES_H
