#ifndef GRAPHTYPES_H_
#define GRAPHTYPES_H_

namespace agile::wk2_partial {

enum class TYPES {
  PERSON,
  FORUMEVENT,
  FORUM,
  PUBLICATION,
  TOPIC,
  PURCHASE,
  SALE,
  AUTHOR,
  INCLUDES,
  HASTOPIC,
  HASORG,
  NONE
};

enum class TRIPLES {
  PERSON_SALE_PERSON_BOMB_BATH,
  PERSON_SALE_PERSON_PRESSURE_COOKER,
  PERSON_SALE_PERSON_AMMUNITION,
  PERSON_SALE_PERSON_ELECTRONICS,
  PERSON_PURCHASE_PERSON_BOMB_BATH,
  PERSON_PURCHASE_PERSON_PRESSURE_COOKER,
  PERSON_PURCHASE_PERSON_AMMUNITION,
  PERSON_PURCHASE_PERSON_ELECTRONICS,
  PERSON_AUTHOR_FORUMEVENT,
  PERSON_AUTHOR_PUBLICATION,
  FORUM_INCLUDES_FORUMEVENT,
  FORUM_HASTOPIC_TOPIC_NYC,
  FORUMEVENT_HASTOPIC_TOPIC_BOMB,
  FORUMEVENT_HASTOPIC_TOPIC_EXPLOSION,
  FORUMEVENT_HASTOPIC_TOPIC_WILLIAMSBURG,
  FORUMEVENT_HASTOPIC_TOPIC_OUTDOORS,
  FORUMEVENT_HASTOPIC_TOPIC_PROSPECT_PARK,
  PUBLICATION_HASORG_TOPIC_NEAR_NYC,
  PUBLICATION_HASTOPIC_TOPIC_ELECTRICAL_ENG,
  NONE
};

constexpr uint64_t NUMTYPES = (uint64_t) TYPES::NONE;
constexpr uint64_t NUMTRIPLES = (uint64_t) TRIPLES::NONE;
using Triples = uint64_t [NUMTRIPLES];

} // namespace agile::wk2_partial

#endif // GRAPHTYPES_H
